### ISSUE TITLE
Icestudio V0.4.0dev can not open "z80-soc-16KB-boot.ice" ?

### ISSUE THREAD

**Issue by albertlu2013** [Obijuan/Z80-FPGA#5]
I use Icestudio  ver 0.4.0-dev .  When I  open file "z80-soc-16KB-boot.ice" , 
It have no show  anything .
What is the version can open it ?

Thanks

**Comment by Obijuan** [comment]
You should use the latest nightly-build icestudio. You can download it from
here:

https://www.icestudio.io/#lk-download

(Download the nightly, not the stable)
